version: "3.8"

services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - APP_URL=http://doc.202330648.lan
      - DB_HOST=db
      - DB_USER=bookstack
      - DB_PASS=bookstackpass
      - DB_DATABASE=bookstack
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: bookstack_db
    environment:
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstackpass
      - MYSQL_ROOT_PASSWORD=rootpass
