network:
  version: 2
  ethernets:
    ens18:
      dhcp4: false
      addresses:
        - 192.168.6.101/24
      routes:
        - to: default
          via: 192.168.6.1
      nameservers:
        addresses:
          -  8.8.8.8
          -  192.168.6.1

