# Fichier : /etc/netplan/50-cloud-init.yaml
# Serveur mail iRedMail - DA 202330648
# IP: 10.20.40.200  DNS (Pi-hole): 10.20.40.100  Domaine: formation.lan

network:
  version: 2
  ethernets:
    eth0:
      dhcp4: no
      addresses:
        - 10.20.40.200/24
      gateway4: 10.20.40.1
      nameservers:
        addresses:
          - 10.20.40.100
        search:
          - formation.lan
